fun main()
{
    val mag1: Magazin = Magazin()
    mag1.Input()
    mag1.Imafine()
    mag1.ReleaseDate()
    mag1.Performance()
    val mag2: Magazin = Magazin()
    mag2.Input()
    mag2.Imafine()
    mag2.ReleaseDate()
    mag2.Performance()
    val mag3: Magazin = Magazin()
    mag3.Input()
    mag3.Imafine()
    mag3.ReleaseDate()
    mag3.Performance()
}